_target_: geobreeze.models.croma.Croma

size: base
modality: optical # 12 channel input
hf_filename: CROMA_base.pt

image_resolution: 120
embed_dim: 768
patch_size: 8

blk_indices:
  segm: [3,5,7,11]
  linear_probe: [8, 9, 10, 11]
  default_cls: [11]