_target_: geobreeze.models.dinov2.DinoV2

torchhub_id: dinov2_vitb14

image_resolution: 224
embed_dim: 768
patch_size: 14

blk_indices:
  segm: [4, 6, 10, 11]
  linear_probe: [8, 9, 10, 11]
  default_cls: [11]