_target_: Dofa

size: base
hf_filename: DOFA_ViT_base_e100.pth

image_resolution: 224
embed_dim: 768
patch_size: 16

blk_indices:
  segm: [3, 5, 7, 11]
  linear_probe: [8, 9, 10, 11]
  default_cls: [11]