bands:
- id: sentinel2/B02
- id: sentinel2/B03
- id: sentinel2/B04
- id: sentinel2/B05
- id: sentinel2/B06
- id: sentinel2/B07
- id: sentinel2/B08
- id: sentinel2/B8A
- id: sentinel2/B11
- id: sentinel2/B12