mode: knn

nb_knn: [1,3,5,10,15,20,25,30]
temperature_list: [0.07]
normmode_list: [all,batchwise,none]

gather_on_cpu: false
n_per_class_list: [-1]
n_tries: 1

args_defining_run:
  task.nb_knn: k
  task.temperature_list: T
  task.normmode_list: norm