defaults:
- optim: sgd

mode: linear_probe

epochs: 50
warmup_epochs: 0
check_val_every_n_epoch: 10
batchwise_spectral_subsampling: 
  train: false
  val: false
  test: false

n_last_blocks_list: [1, 4]
pooling: [avgpool, cls, default]
lr: [1e-5,  5e-5, 1e-4, 5e-4, 1e-3, 5e-3, 1e-2, 5e-2, 0.1, 0.5, 1,5,10]
use_additional_1dbatchnorm_list: [true]

args_defining_run:
  dl.batch_size: "bsz"
  optim.epochs: "e"