model_type: croma
image_resolution: 120

size: base
modality: optical # 12 channel input
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/CROMA_base.pt
embed_dim: 768

segm_blk_indices: [3,5,7,11]
accel_cls_blk_indices: [8, 9, 10, 11]
default_cls_blk_indices: [11]
default_feat_out_dim: 768

replace_pe: true
patch_size: 8