model_type: dinov2

dinov2_torchhub_id: dinov2_vitb14
image_resolution: 224
embed_dim: 768

segm_blk_indices: [4,6,10,11]
accel_cls_blk_indices: [8, 9, 10, 11]
default_cls_blk_indices: [11]
default_feat_out_dim: 768

replace_pe: true
patch_size: 14 # only needed for replace_pe