model_type: dofa

size: base
image_resolution: 224
embed_dim: 768
pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/DOFA_ViT_base_e100.pth

segm_blk_indices: [3, 5, 7, 11]
accel_cls_blk_indices: [8, 9, 10, 11]
default_cls_blk_indices: [11]
default_feat_out_dim: 768
