dataset_type: null
task: null  # Options: "classification", "segmentation", 'regressopm'
num_classes: null
num_channels: null
data_path: null
wavelengths_mean_nm: null
wavelengths_sigma_nm: null
wavelengths_mean_microns: null
multilabel: null
image_resolution: null #what resolution to use for the images
subset:
  train: -1
  val: -1
  test: -1
input_key: null
sequence_length: null #for time series datasets: T goes into the C dimension
band_gsds: null #for senpamae: list of GSDs for each band
scale: 1.0 #for downscaling images
normalize_target: true