defaults:
  - base_dataset

dataset_type: corine
task: classification
dataset_name: spectral_earth # for band_ids
num_classes: 19
num_channels: 10
data_path: ${oc.env:DATASETS_DIR}/spectral_earth
image_resolution: 128
multilabel: true
full_spectra: true # for wavelengths_mean_nm and wavelengths_sigma_nm

# Target dataset
target_dataset_name: dummy_s2_10b

senpamae_channels: #senpamae SRF has only 10 channels (S2-10/20m), so indexes below are relative to that list
  - 0
  - 1
  - 2
  - 7

senpamae_srf_name: rfs_sentinel2_a.npy



