defaults:
  - base_dataset

dataset_type: corine
task: classification
dataset_name: spectral_earth # for band_ids
num_classes: 19
num_channels: 202
data_path: ${oc.env:DATASETS_DIR}/spectral_earth
image_resolution: 128
multilabel: true
senpamae_srf_name: rfs_enmap_recon.npy