defaults:
  - base_dataset

dataset_type: hyperview
task: regression
dataset_name: hyperview #for band_ids
num_classes: 4
num_channels: 16
data_path: ${oc.env:DATASETS_DIR}/hyperview
image_resolution: 224

# Target dataset
target_dataset_name: dummy-modis

band_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
senpamae_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
band_gsds: [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30]
senpamae_srf_name: rfs_modis_terra.npy