band_names:
  - "02 - Blue"
  - "03 - Green"
  - "04 - Red"
  - "05 - NIR"
  - "06 - SWIR1"
  - "07 - SWIR2"
num_channels: 6
wavelengths_mean_nm: [482, 561, 654, 865, 1609, 2204]
wavelengths_sigma_nm: [23, 22, 14, 11, 34, 76]
band_gsds: [15, 15, 15, 15, 15, 15]
senpamae_channels: #senpamae SRF has only 10 channels (S2-10/20m), so indexes below are relative to that list
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
# has 7 bands: B1 thru B7
# forestnet uses 6bands: B2[0] thru B7[5] 
senpamae_srf_name: rfs_landsat.npy 