band_names:
  - "02 - Blue"
  - "03 - Green"
  - "04 - Red"
  - "05 - Vegetation Red Edge"
  - "06 - Vegetation Red Edge"
  - "07 - Vegetation Red Edge"
  - "08 - NIR"
  - "08A - Vegetation Red Edge"
  - "11 - SWIR"
  - "12 - SWIR"
num_channels: 10
wavelengths_mean_nm: [492, 559, 664, 704, 741, 782, 827, 865, 1613, 2203]
wavelengths_sigma_nm: [24, 13, 12, 5, 5, 7, 37, 8, 34, 64]
band_gsds: [10, 10, 10, 20, 20, 20, 10, 20, 20, 20]
senpamae_channels: #senpamae SRF has only 10 channels (listed above), so indexes below are relative to that list
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
senpamae_srf_name: rfs_sentinel2_a.npy