band_names:
  - "02 - Blue"
  - "03 - Green"
  - "04 - Red"
  - "08 - NIR"
num_channels: 4
wavelengths_mean_nm: [492, 559, 664, 827]
wavelengths_sigma_nm: [24, 13, 12,  37]
band_gsds: [10, 10, 10, 10]
senpamae_channels: #senpamae SRF has only 10 channels (listed above), so indexes below are relative to that list
  - 0
  - 1
  - 2
  - 6
senpamae_srf_name: rfs_sentinel2_a.npy