defaults:
  - base_dataset
  - wv_8b

dataset_type: spacenet1
task: segmentation
dataset_name: fmow_wv23 #for band_ids
num_classes: 2
num_channels: 8
data_path: ${oc.env:DATASETS_DIR}/spacenet1
image_resolution: 224
multilabel: false