model_type: anysat
embed_dim: 768
image_resolution: 224

anysat_torchhub_id: anysat

segm_blk_indices: [2, 3, 4, 5]
accel_cls_blk_indices: [5]
default_cls_blk_indices: [5]

input_key: naip
patch_size: 20 #in m.