model_type: galileo
embed_dim: 768
image_resolution: 120

pretrained_path: ${oc.env:MODEL_WEIGHTS_DIR}/galileo/encoder.pt

segm_blk_indices: [3, 5, 7, 11]
accel_cls_blk_indices: [8, 9, 10, 11]
default_cls_blk_indices: [11]

input_key: s2

patch_size: 12