model_type: panopticon
image_resolution: 224
embed_dim: 768
patch_size: 14

run_dir: /hkfs/work/workspace/scratch/tum_mhj8661-panopticon/dino_logs/abl_a3_s2/v9_16gpu/ds=fmow-800k^satl^mme^spee_lr=5e-4_augm=v4_c13_e=70_model=stg1_16gpu/lr=5e-4_warmup=5_hold_epochs=0_min_lr=1e-6_frz=last_layer=1_break_at_epochs=-1_bsz=75/model_0056249.pth

segm_blk_indices: [3, 5, 7, 11]
accel_cls_blk_indices: [8, 9, 10, 11]
default_cls_blk_indices: [11]
default_feat_out_dim: 768