n_last_blocks_list: [1, 4]
pooling: [avgpool, cls, default]
lr: [1e-5,  5e-5, 1e-4, 5e-4, 1e-3, 5e-3, 1e-2, 5e-2, 0.1, 0.5, 1,5,10]
use_additional_1dbatchnorm_list: [true]
optim: ${_optims.sgd}

_optims:
  sgd:
    id: SGD
    display_name: sgd
    momentum: 0.9
    weight_decay: 0

  adamw:
    id: AdamW
    display_name: adamw
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.01
  
  adam:
    id: Adam
    display_name: adam
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.01