bands:
- id: modis_terra/B01
- id: modis_terra/B02
- id: modis_terra/B03
- id: modis_terra/B04
- id: modis_terra/B05
- id: modis_terra/B06
- id: modis_terra/B07
- id: modis_terra/B08
- id: modis_terra/B09
- id: modis_terra/B10
- id: modis_terra/B11
- id: modis_terra/B12
- id: modis_terra/B13
- id: modis_terra/B14
- id: modis_terra/B15
- id: modis_terra/B16
