bands:
- id: enmap/B001
- id: enmap/B002
- id: enmap/B003
- id: enmap/B004
- id: enmap/B005
- id: enmap/B006
- id: enmap/B007
- id: enmap/B008
- id: enmap/B009
- id: enmap/B010
- id: enmap/B011
- id: enmap/B012
- id: enmap/B013
- id: enmap/B014
- id: enmap/B015
- id: enmap/B016
- id: enmap/B017
- id: enmap/B018
- id: enmap/B019
- id: enmap/B020
- id: enmap/B021
- id: enmap/B022
- id: enmap/B023
- id: enmap/B024
- id: enmap/B025
- id: enmap/B026
- id: enmap/B027
- id: enmap/B028
- id: enmap/B029
- id: enmap/B030
- id: enmap/B031
- id: enmap/B032
- id: enmap/B033
- id: enmap/B034
- id: enmap/B035
- id: enmap/B036
- id: enmap/B037
- id: enmap/B038
- id: enmap/B039
- id: enmap/B040
- id: enmap/B041
- id: enmap/B042
- id: enmap/B043
- id: enmap/B044
- id: enmap/B045
- id: enmap/B046
- id: enmap/B047
- id: enmap/B048
- id: enmap/B049
- id: enmap/B050
- id: enmap/B051
- id: enmap/B052
- id: enmap/B053
- id: enmap/B054
- id: enmap/B055
- id: enmap/B056
- id: enmap/B057
- id: enmap/B058
- id: enmap/B059
- id: enmap/B060
- id: enmap/B061
- id: enmap/B062
- id: enmap/B063
- id: enmap/B064
- id: enmap/B065
- id: enmap/B066
- id: enmap/B067
- id: enmap/B068
- id: enmap/B069
- id: enmap/B070
- id: enmap/B071
- id: enmap/B072
- id: enmap/B073
- id: enmap/B074
- id: enmap/B075
- id: enmap/B076
- id: enmap/B077
- id: enmap/B078
- id: enmap/B079
- id: enmap/B080
- id: enmap/B081
- id: enmap/B082
- id: enmap/B083
- id: enmap/B084
- id: enmap/B085
- id: enmap/B086
- id: enmap/B087
- id: enmap/B088
- id: enmap/B089
- id: enmap/B090
- id: enmap/B091
- id: enmap/B092
- id: enmap/B093
- id: enmap/B094
- id: enmap/B095
- id: enmap/B096
- id: enmap/B097
- id: enmap/B098
- id: enmap/B099
- id: enmap/B100
- id: enmap/B101
- id: enmap/B102
- id: enmap/B103
- id: enmap/B104
- id: enmap/B105
- id: enmap/B106
- id: enmap/B107
- id: enmap/B108
- id: enmap/B109
- id: enmap/B110
- id: enmap/B111
- id: enmap/B112
- id: enmap/B113
- id: enmap/B114
- id: enmap/B115
- id: enmap/B116
- id: enmap/B117
- id: enmap/B118
- id: enmap/B119
- id: enmap/B120
- id: enmap/B121
- id: enmap/B122
- id: enmap/B123
- id: enmap/B124
- id: enmap/B125
- id: enmap/B126
- id: enmap/B142
- id: enmap/B143
- id: enmap/B144
- id: enmap/B145
- id: enmap/B146
- id: enmap/B147
- id: enmap/B148
- id: enmap/B149
- id: enmap/B150
- id: enmap/B151
- id: enmap/B152
- id: enmap/B153
- id: enmap/B154
- id: enmap/B155
- id: enmap/B156
- id: enmap/B157
- id: enmap/B158
- id: enmap/B159
- id: enmap/B160
- id: enmap/B168
- id: enmap/B169
- id: enmap/B170
- id: enmap/B171
- id: enmap/B172
- id: enmap/B173
- id: enmap/B174
- id: enmap/B175
- id: enmap/B176
- id: enmap/B177
- id: enmap/B178
- id: enmap/B179
- id: enmap/B180
- id: enmap/B181
- id: enmap/B182
- id: enmap/B183
- id: enmap/B184
- id: enmap/B185
- id: enmap/B186
- id: enmap/B187
- id: enmap/B188
- id: enmap/B189
- id: enmap/B190
- id: enmap/B191
- id: enmap/B192
- id: enmap/B193
- id: enmap/B194
- id: enmap/B195
- id: enmap/B196
- id: enmap/B197
- id: enmap/B198
- id: enmap/B199
- id: enmap/B200
- id: enmap/B201
- id: enmap/B202
- id: enmap/B203
- id: enmap/B204
- id: enmap/B205
- id: enmap/B206
- id: enmap/B207
- id: enmap/B208
- id: enmap/B209
- id: enmap/B210
- id: enmap/B211
- id: enmap/B212
- id: enmap/B213
- id: enmap/B214
- id: enmap/B215
- id: enmap/B216
- id: enmap/B217
- id: enmap/B218
- id: enmap/B219
- id: enmap/B220
- id: enmap/B221
- id: enmap/B222
- id: enmap/B223
- id: enmap/B224