defaults:
  - base_dataset

dataset_type: corine
task: classification
dataset_name: spectral_earth # for band_ids
num_classes: 19
num_channels: 4
data_path: ${oc.env:DATASETS_DIR}/spectral_earth
image_resolution: 128
multilabel: true
full_spectra: true # for wavelengths_mean_nm and wavelengths_sigma_nm

# Target dataset
target_dataset_name: dummy-superdove
band_ids: [1, 3, 5, 7] # to subset the SD 8 bands
#one-to-one mapping of SD bands
# using Blue, Green, Red, NIR
senpamae_channels: 
  - 1
  - 3
  - 5
  - 7
band_gsds: [4, 4, 4, 4]
senpamae_srf_name: rfs_superdove.npy


