defaults:
  - base_dataset

dataset_type: corine
task: classification
dataset_name: spectral_earth # for band_ids
num_classes: 19
num_channels: 16
data_path: ${oc.env:DATASETS_DIR}/spectral_earth
image_resolution: 128
multilabel: true
full_spectra: true # for wavelengths_mean_nm and wavelengths_sigma_nm

# Target dataset
target_dataset_name: dummy-modis

band_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
senpamae_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
band_gsds: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
senpamae_srf_name: rfs_modis_terra.npy

subset:
 train: 0.1
 val: -1
 test: -1