defaults:
  - base_dataset

dataset_type: digital_typhoon
task: regression
dataset_name: digital_typhoon
num_classes: 1
num_channels: 3 # dataset comes in sequences of 3, height, width by default
data_path: ${oc.env:DATASETS_DIR}/DigitalTyphoon
image_resolution: 224
multilabel: false
sequence_length: 3 # number of timesteps in the sequence
wavelengths_mean_nm: [10400, 10400, 10400]
wavelengths_sigma_nm: [250, 250, 250]

subset:
  train: 0.1
  val: 0.2
  test: -1