defaults:
  - base_dataset

dataset_type: fmow
task: classification
dataset_name: fmow_qbge #for band_ids
num_classes: 62
num_channels: 4 # RGB, NIR
keep_sensors: ['QUICKBIRD02', 'GEOEYE01']
data_path: ${oc.env:DATASETS_DIR}
image_resolution: 224
multilabel: false
#QB,GE is B,G,R,NIR -> B2[0], B3[1], B4[2], B8[6]
senpamae_channels: #senpamae SRF has only 10 channels (S2-10/20m), so indexes below are relative to that list
  - 0
  - 1
  - 2
  - 6
band_gsds: [1, 1, 1, 1] #approx GSD of QB,GE
senpamae_srf_name: rfs_sentinel2_a.npy
#above:
# mapping RGB,NIR -> S2-10/20m
# B3 -> B4 [2] (red)
# B2 -> B3 [0] (green)
# B1 -> B2 [1] (blue)
# B3 -> B8 [6] (NIR)
subset:
  train: 0.1
  val: 0.1
  test: -1