defaults:
  - geobench
  - s2_10b


num_channels: 2
benchmark_name: classification_v1.0
dataset_name: m-so2sat
task: classification
num_classes: 17
multilabel: false


wavelengths_mean_nm: [-2,-1]
wavelengths_sigma_nm: [24, 13, 12, 5, 5, 7, 37, 8, 34, 64]
band_gsds: [10, 10, 10, 20, 20, 20, 10, 20, 20, 20]

NOT DONE YET!!!