defaults:
  - geobench

benchmark_name: segmentation_v1.0
dataset_name: m-chesapeake
task: segmentation
band_names:
  - "Blue"
  - "Green"
  - "Red"
  - "NearInfrared"

wavelengths_mean_nm: [490, 560, 665,876]
wavelengths_sigma_nm: [16, 16, 16, 16]
num_classes: 7
multilabel: false
num_channels: 4