defaults:
  - base_dataset

dataset_type: hyperview
task: classification
dataset_name: hyperview #for band_ids
num_classes: 4
num_channels: 150
data_path: ${oc.env:DATASETS_DIR}/hyperview
image_resolution: 224
multilabel: false
full_spectra: true # for wavelengths_mean_nm and wavelengths_sigma_nm