defaults:
  - base_dataset

dataset_type: hyperview
task: regression
dataset_name: hyperview #for band_ids
num_classes: 4
num_channels: 10
data_path: ${oc.env:DATASETS_DIR}/hyperview
image_resolution: 224
band_ids: [6, 18, 42, 59, 70, 82, 102, 109, 126, 144] #random selection from 10 bins
full_spectra: true # for wavelengths_mean_nm and wavelengths_sigma_nm