defaults:
  - base_dataset

dataset_type: hyperview
task: regression
dataset_name: hyperview #for band_ids
num_classes: 4
num_channels: 8
data_path: ${oc.env:DATASETS_DIR}/hyperview
image_resolution: 224

target_dataset_name: dummy-superdove
band_ids: [0, 1, 2, 3, 4, 5, 6, 7]
senpamae_srf_name: rfs_superdove.npy