band_names:
  - "02 - Blue"
  - "03 - Green"
  - "04 - Red"
  - "05 - NIR"
num_channels: 4
wavelengths_mean_nm: [482, 561, 654, 865]
wavelengths_sigma_nm: [23, 22, 14, 11]
band_gsds: [15, 15, 15, 15]
senpamae_channels: #senpamae SRF has only 10 channels (S2-10/20m), so indexes below are relative to that list
  - 1
  - 2
  - 3
  - 4
# has 7 bands: B1 thru B7
# forestnet uses 6bands: B2[0] thru B7[5] 
senpamae_srf_name: rfs_landsat.npy 
#above:
# mapping RGB,NIR -> L8 7 bands
# B2 -> B4 [1] (red)
# B3 -> B3 [2] (green)
# B4 -> B2 [3] (blue)
# B5 -> B5 [4] (NIR)