band_names:
  - "08 - NIR"
  
num_channels: 1
wavelengths_mean_nm: [827]
wavelengths_sigma_nm: [37]
band_gsds: [10]
senpamae_channels: #senpamae SRF has only 10 channels (listed above), so indexes below are relative to that list
  - 6
senpamae_srf_name: rfs_sentinel2_a.npy