defaults:
  - base_dataset
  - wv_8b

dataset_type: spacenet1
task: segmentation
dataset_name: fmow_wv23 #for band_ids
num_classes: 2
num_channels: 8
#employs a 70:10:20 split for train:val:test
data_path: ${oc.env:DATASETS_DIR}/spacenet1_v2
image_resolution: 224
multilabel: false