num_channels: 8
wavelengths_mean_nm: [428, 482, 545, 604, 660, 723, 824, 906]
wavelengths_sigma_nm: [18, 22, 27, 15, 23, 15, 42, 36]
band_gsds: [1, 1, 1, 1, 1, 1, 1, 1]
senpamae_channels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
senpamae_srf_name: rfs_wv23_recon.npy