output_dir:
seed: 21
num_gpus: 1
add_defining_args: true
resume: true
logger: mlflow
overwrite: false

model:
  _target_: null

data:
  task: null

  train: 
    _target_: null
    transform: null
  
  val:
    _target_: null
    transform: null

  test:
    _target_: null
    transform: null


# specific to training_mode
optim: null

dl:
  num_workers: 8
  pin_memory: true
  batch_size: 256


_vars:
  augm: # default augmentations
    cls:

      train:
      - _target_: K.RandomHorizontalFlip
        p: 0.5
        keepdim: true
      - _target_: K.RandomVerticalFlip
        p: 0.5
        keepdim: true
      # - _target_: K.RandomResizedCrop
      #   # size: ["${model.image_resolution}", "${model.image_resolution}"]
      #   scale: [0.8, 1.0]
      #   size: [224,224]
      - _target_: K.Resize
        size: "${model.image_resolution}"
        keepdim: true

      val:
      - _target_: K.Resize
        size: "${model.image_resolution}"
        keepdim: true

  segm:
    train:
